# ========================== MOSQUITTO BROKER CONFIG ==========================

# Enable persistence to store messages and subscriptions across restarts
persistence true

# Set the location for persistent data (e.g., retained messages, subscriptions)
persistence_location /mosquitto/data/

# Allow anonymous connections (for testing purposes only)
allow_anonymous true

# Setup logging to a file
log_dest file /mosquitto/log/mosquitto.log

# Log to stdout for Docker logs
# log_dest stdout

listener 1883   # Expose the default MQTT port for unencrypted connections
listener 8883   # Expose the default MQTT port for encrypted connections (TLS/SSL)
listener 9001   # Expose the default MQTT port for WebSocket connections